# Configurações para perfil de teste
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      timeout: 2000ms

# Configurações específicas da aplicação para teste
app:
  storage:
    base-path: /tmp/pdf-processor-test
  security:
    api-keys:
      - "test-api-key"

logging:
  level:
    com.pdfprocessor: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    root: INFO