# Configuração do Worker PDF Processor
spring:
  application:
    name: pdf-processor-worker
  
  # Configuração Redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Configurações específicas do worker
worker:
  enabled: true
  polling-interval-seconds: 5
  max-retries: 3

# Storage configuration
storage:
  local:
    base-path: ./storage

# Logging
logging:
  level:
    com.pdfprocessor: INFO
    org.springframework.data.redis: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Server configuration (para actuator)
server:
  port: 8081